import 'package:bilibili_audio_downloader/theme/brand.dart';
import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FThemeData get slateLight {
  const colors = FColors(
    brightness: .light,
    systemOverlayStyle: .dark,
    barrier: Color(0x33000000),
    background: Color(0xfff8fafc),
    foreground: Color(0xFF0a0a0a),
    primary: Color(0xFF171717),
    primaryForeground: Color(0xFFfafafa),
    secondary: Color(0xFFf5f5f5),
    secondaryForeground: Color(0xFF171717),
    muted: Color(0xFFf5f5f5),
    mutedForeground: Color(0xFF737373),
    destructive: Color(0xFFEF4444),
    destructiveForeground: Color(0xFFF8FAFC),
    error: Color(0xFFEF4444),
    errorForeground: Color(0xFFF8FAFC),
    border: Color(0xFFE2E8F0),
  );

  final typography = _typography(colors: colors);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(
    colors: colors,
    typography: typography,
    style: style,
    extensions: [
      BrandColor(
        color: Color(0xFFffffff),
        inputBackGroundColor: Color(0xFFffffff),
        containerColor: Color(0xFFffffff),
        bottomNavigationBarColor: Color(0xFFffffff),
        iconColor: Color(0xFF171717),
        shadowColor: Colors.grey.shade200,
        textColor: Colors.grey.shade600,
      ),
    ],
  );
}

FThemeData get slateDark {
  const colors = FColors(
    brightness: .dark,
    systemOverlayStyle: .light,
    barrier: Color(0x7A000000),
    background: Color(0xFF0a0a0a),
    foreground: Color(0xFFfafafa),
    primary: Color(0xFFe5e5e5),
    primaryForeground: Color(0xFF171717),
    secondary: Color(0xFF262626),
    secondaryForeground: Color(0xFFfafafa),
    muted: Color(0xFF262626),
    mutedForeground: Color(0xFFa1a1a1),
    destructive: Color(0xFF7F1D1D),
    destructiveForeground: Color(0xFFF8FAFC),
    error: Color(0xFF7F1D1D),
    errorForeground: Color(0xFFF8FAFC),
    border: Color(0xFF1E293B),
  );

  final typography = _typography(colors: colors);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(
    colors: colors,
    typography: typography,
    style: style,
    extensions: [
      BrandColor(
        color: Color(0xff000000),
        inputBackGroundColor: Color(0xFF151515),
        containerColor: Color(0xFF171717),
        bottomNavigationBarColor: Color(0xFF1d1d1d),
        iconColor: Color(0xFFfafafa),
        shadowColor: Colors.black.withAlpha(0x1A),
        textColor: Colors.grey.shade600,
      ),
    ],
  );
}

FTypography _typography({
  required FColors colors,
  String defaultFontFamily = 'packages/forui/Inter',
}) => FTypography(
  xs: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 12,
    height: 1,
  ),
  sm: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 14,
    height: 1.25,
  ),
  base: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 16,
    height: 1.5,
  ),
  lg: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 18,
    height: 1.75,
  ),
  xl: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 20,
    height: 1.75,
  ),
  xl2: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 22,
    height: 2,
  ),
  xl3: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 30,
    height: 2.25,
  ),
  xl4: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 36,
    height: 2.5,
  ),
  xl5: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 48,
    height: 1,
  ),
  xl6: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 60,
    height: 1,
  ),
  xl7: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 72,
    height: 1,
  ),
  xl8: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 96,
    height: 1,
  ),
);

FStyle _style({required FColors colors, required FTypography typography}) =>
    FStyle(
      formFieldStyle: .inherit(colors: colors, typography: typography),
      focusedOutlineStyle: FFocusedOutlineStyle(
        color: colors.primary,
        borderRadius: const .all(.circular(8)),
      ),
      iconStyle: IconThemeData(color: colors.primary, size: 20),
      tappableStyle: FTappableStyle(),
      borderRadius: const FLerpBorderRadius.all(.circular(8), min: 24),
      borderWidth: 1,
      pagePadding: const .symmetric(vertical: 8, horizontal: 12),
      shadow: const [
        BoxShadow(
          color: Color(0x0d000000),
          offset: Offset(0, 1),
          blurRadius: 2,
        ),
      ],
    );
